use std::str::Split;

use fastnum::D256;

use crate::{enums::Incoming,
            ib_frame::{ParseError, ParseIbkrFrame, ParseResult},
            utils::ib_message::decode,
            ServerVersion};

/// the commission and fees generated by an execution.
#[derive(Default, Debug, Clone)]
pub struct CommissionAndFeesReport {
    /// the execution's id this commission and fees belongs to.
    pub exec_id:               String,
    /// the commission and fees cost.
    pub commission_and_fees:   D256,
    /// the reporting currency.
    pub currency:              String,
    /// the realized profit and loss
    pub realized_pnl:          Option<D256>,
    /// The income return.
    pub yield_amount:          Option<D256>,
    /// date expressed in yyyymmdd format.
    pub yield_redemption_date: Option<i32>,
}
impl ParseIbkrFrame for CommissionAndFeesReport {
    fn try_parse_frame(
        msg_id: Incoming,
        server_version: Option<ServerVersion>,
        it: &mut Split<&str>,
    ) -> ParseResult<Self>
    where
        Self: Sized,
    {
        if !matches!(msg_id, Incoming::CommissionReport) {
            return Err(ParseError::UnexpectedMessage);
        }
        it.next(); // skip version
        Ok(Self {
            exec_id:               decode(it)?.unwrap(),
            commission_and_fees:   decode(it)?.unwrap(),
            currency:              decode(it)?.unwrap(),
            realized_pnl:          decode(it)?,
            yield_amount:          decode(it)?,
            yield_redemption_date: decode(it)?,
        })
    }
}
